# Generated by Django 5.1 on 2024-08-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_privateroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
