# Generated by Django 5.1.2 on 2024-10-25 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refer', to='chat.message', verbose_name='Родитель'),
        ),
        migrations.DeleteModel(
            name='PrivateRoom',
        ),
    ]
